{% set name = "apache-airflow-providers-microsoft-azure" %}
{% set version = "11.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_microsoft_azure-{{ version }}.tar.gz
  sha256: 9f695f442592d8c0485ae7624303d16776e44f060bdbc920bd5e4f1a11986839

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - adal >=1.2.7
    - adlfs >=2023.10.0
    - apache-airflow >=2.8.0
    - azure-batch >=8.0.0
    - azure-cosmos >=4.6.0
    - azure-datalake-store >=0.0.45
    - azure-identity >=1.3.1
    - azure-keyvault-secrets >=4.1.0
    - azure-kusto-data >=4.1.0,!=4.6.0
    - azure-mgmt-containerinstance >=10.1.0
    - azure-mgmt-containerregistry >=8.0.0
    - azure-mgmt-cosmosdb >=3.0.0
    - azure-mgmt-datafactory >=2.0.0
    - azure-mgmt-datalake-store >=0.5.0
    - azure-mgmt-resource >=2.2.0
    - azure-mgmt-storage >=16.0.0
    - azure-servicebus >=7.12.1
    - azure-storage-blob >=12.14.0
    - azure-storage-file-datalake >=12.9.1
    - azure-storage-file-share >=12.7.0
    - azure-synapse-artifacts >=0.17.0
    - azure-synapse-spark >=0.2.0
    - microsoft-kiota-abstractions <1.4.0
    - microsoft-kiota-http >=1.3.0,!=1.3.4
    - microsoft-kiota-serialization-json ==1.0.0
    - microsoft-kiota-serialization-text ==1.0.0
    - msgraph-core >=1.0.0

test:
  imports:
    - airflow.providers.microsoft.azure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-microsoft-azure for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: airflow/providers/microsoft/azure/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
