{% set name = "apache-airflow-providers-microsoft-azure" %}
{% set version = "8.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_microsoft_azure-{{ version }}.tar.gz
  sha256: 1b018769d31c843d16bd4cf59438846ded40a585a1a2b90617d3ca5f2a280b6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - adal >=1.2.7
    - adlfs >=2023.10.0
    - apache-airflow >=2.6.0
    - azure-batch >=8.0.0
    - azure-cosmos >=4.0.0
    - azure-datalake-store >=0.0.45
    - azure-identity >=1.3.1
    - azure-keyvault-secrets >=4.1.0
    - azure-kusto-data >=4.1.0
    - azure-mgmt-containerinstance >=9.0.0
    - azure-mgmt-containerregistry >=8.0.0
    - azure-mgmt-cosmosdb
    - azure-mgmt-datafactory >=2.0.0
    - azure-mgmt-datalake-store >=0.5.0
    - azure-mgmt-resource >=2.2.0
    - azure-mgmt-storage >=16.0.0
    - azure-servicebus >=7.6.1
    - azure-storage-blob >=12.14.0
    - azure-storage-file-datalake >=12.9.1
    - azure-storage-file-share
    - azure-synapse-artifacts >=0.17.0
    - azure-synapse-spark

test:
  imports:
    - apache_airflow_providers_microsoft_azure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-microsoft-azure for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: airflow/providers/microsoft/azure/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
