{% set name = "apache-airflow-providers-microsoft-azure" %}
{% set version = "12.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_microsoft_azure-{{ version }}.tar.gz
  sha256: de5d04aca62d54b60e8a4d88e7cfde6269e9b98846882c09d4d89120d86eeb4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - apache-airflow-providers-common-compat >=1.8.0
    - msgraphfs >=0.3.0
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - adlfs >=2023.10.0
    - azure-batch >=8.0.0
    - azure-cosmos >=4.6.0
    - azure-mgmt-cosmosdb >=3.0.0
    - azure-datalake-store >=0.0.45
    - azure-identity >=1.3.1
    - azure-keyvault-secrets >=4.1.0
    - azure-mgmt-datalake-store >=0.5.0
    - azure-mgmt-resource >=2.2.0
    - azure-storage-blob >=12.26.0
    - azure-mgmt-storage >=16.0.0
    - azure-storage-file-share >=12.7.0
    - azure-servicebus >=7.12.1
    - azure-synapse-spark >=0.2.0
    - azure-synapse-artifacts >=0.17.0
    - adal >=1.2.7
    - azure-storage-file-datalake >=12.9.1
    - azure-kusto-data >=4.1.0,!=4.6.0
    - azure-mgmt-datafactory >=2.0.0
    - azure-mgmt-containerregistry >=8.0.0
    - azure-mgmt-containerinstance >=10.1.0
    - msgraph-core >=1.3.3
    - microsoft-kiota-authentication-azure >=1.9.4,<2.0.0
    - microsoft-kiota-http >=1.9.4,<2.0.0
    - microsoft-kiota-serialization-json >=1.9.4
    - microsoft-kiota-serialization-text >=1.9.4
    - microsoft-kiota-abstractions >=1.9.4,<2.0.0
    - msal_extensions >=1.3.0

test:
  imports:
    - airflow.providers.microsoft.azure
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-microsoft-azure for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: src/airflow/providers/microsoft/azure/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
