{% set name = "apache-airflow-providers-microsoft-azure" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-microsoft-azure-{{ version }}.tar.gz
  sha256: 958010047b7528b5e1d03493526b1ddd3bf18fda96b5de96d24bbf165f54442e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.2.0
    - azure-batch >=8.0.0
    - azure-cosmos >=4.0.0
    - azure-datalake-store >=0.0.45
    - azure-identity >=1.3.1
    - azure-keyvault-secrets >=4.1.0,<5.0
    - azure-kusto-data >=0.0.43,<0.1
    - azure-mgmt-containerinstance >=1.5.0,<2.0
    - azure-mgmt-datafactory >=1.0.0,<2.0
    - azure-mgmt-datalake-store >=0.5.0
    - azure-mgmt-resource >=2.2.0
    - azure-servicebus >=7.6.1
    - azure-storage-blob >=12.7.0,<12.9.0
    - azure-storage-common >=2.1.0
    - azure-storage-file >=2.1.0

test:
  imports:
    - airflow.providers.microsoft.azure
    - airflow.providers.microsoft.azure.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-microsoft-azure package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
